build:
    environment:
        php:
            version: 8.0
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=embeddables-coverage'
                coverage:
                    file: 'embeddables-coverage'
                    format: 'clover'
