language: php
sudo: false

php:
    - 5.6
    - 7.0
    - 7.1

env:
    global:
        - TEST_COMMAND="composer test"

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - $TEST_COMMAND
